name: Build DesktopExporter (Windows)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "requirements.txt"
      - "icon.ico"
      - "logo.png"
      - ".github/workflows/build-windows.yml"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller (cmd)
        shell: cmd
        run: |
          pyinstaller --noconfirm --onefile --windowed ^
            --name DesktopExporter ^
            --icon icon.ico ^
            --add-data "logo.png;." ^
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DesktopExporter-Windows
          path: dist/DesktopExporter.exe
